### ISSUE TITLE
UX feedback

### ISSUE THREAD

**Issue by sw-yx** [one-aalam/svelte-starter-kit#14]
for the supabase fork, i recommend to show some kind of landing page first before showing the auth page. this would probably make for a more useful starter

![CleanShot 2021-06-02 at 18 22 59](https://user-images.githubusercontent.com/6764957/120464530-9c213280-c3cf-11eb-9a04-4d16bbad0915.png)

also should include supabase setup instructions other wise you get this

```
404
Not found: /undefined/auth/v1/authorize

Error: Not found: /undefined/auth/v1/authorize
    at render_page (file:///Users/swyx/Work/testbeds/svelte-starter-kit/node_modules/@sveltejs/kit/dist/ssr.js:1187:11)
    at async render (file:///Users/swyx/Work/testbeds/svelte-starter-kit/node_modules/@sveltejs/kit/dist/ssr.js:1493:12)
    at async Object.handle (/Users/swyx/Work/testbeds/svelte-starter-kit/src/hooks/index.ts:25:22)
    at async ssr (file:///Users/swyx/Work/testbeds/svelte-starter-kit/node_modules/@sveltejs/kit/dist/ssr.js:1456:10)
    at async Immediate.<anonymous> (file:///Users/swyx/Work/testbeds/svelte-starter-kit/node_modules/@sveltejs/kit/dist/chunks/index.js:3301:23)
```

**Comment by one-aalam** [comment]
Thanks @sw-yx  for pointing these out.

I'll try to incorporate these by the next update pretty soon.

**Comment by one-aalam** [comment]
@sw-yx the `auth-supabase` branch has following changes available now
- You should see something like 
<img width="1668" alt="ssk-2" src="https://user-images.githubusercontent.com/532906/120828240-ea723500-c579-11eb-98da-f5775c1132f9.png">
as the  `/` landing page now
- `/auth` serves the sign-in/sign-up experience now
- Updated README to contain the set-up instruction now

**Comment by sw-yx** [comment]
nice! :)
