### ISSUE TITLE
ModelBackdrop and NavBar console error

### ISSUE THREAD

**Issue by Ak4zh** [one-aalam/svelte-starter-kit#30]
When you are not logged-in, the app still tried to generate a refresh token using the undefined user and causes a non-recoverable error.

```
proxy.js:15 [HMR][Svelte] Unrecoverable error in <ModalBackdrop>: next update will trigger a full reload
logError @ proxy.js:15
Proxy<ModalBackdrop> @ proxy.js:377
create_fragment @ __layout.svelte? [sm]:19
init @ index.mjs:1877
_layout @ __layout.svelte? [sm]:25
createProxiedComponent @ svelte-hooks.js:266
ProxyComponent @ proxy.js:239
Proxy<__layout> @ proxy.js:346
create_if_block_2 @ root.svelte? [sm]:37
create_fragment @ root.svelte? [sm]:36
init @ index.mjs:1877
Root @ root.svelte? [sm]:16
createProxiedComponent @ svelte-hooks.js:266
ProxyComponent @ proxy.js:239
Proxy<Root> @ proxy.js:346
_init @ start.js:885
start @ start.js:738
await in start (async)
start @ start.js:1373
(anonymous) @ (index):22369
index.mjs:1857 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')
    at init (index.mjs:1857:50)
    at new ModalBackdrop (ModalBackdrop.svelte? [sm]:7:70)
    at createProxiedComponent (svelte-hooks.js:266:9)
    at new ProxyComponent (proxy.js:239:20)
    at new Proxy<ModalBackdrop> (proxy.js:346:11)
    at create_fragment (__layout.svelte? [sm]:19:17)
    at init (index.mjs:1877:37)
    at new _layout (__layout.svelte? [sm]:25:57)
    at createProxiedComponent (svelte-hooks.js:266:9)
    at new ProxyComponent (proxy.js:239:20)
init @ index.mjs:1857
ModalBackdrop @ ModalBackdrop.svelte? [sm]:7
createProxiedComponent @ svelte-hooks.js:266
ProxyComponent @ proxy.js:239
Proxy<ModalBackdrop> @ proxy.js:346
create_fragment @ __layout.svelte? [sm]:19
init @ index.mjs:1877
_layout @ __layout.svelte? [sm]:25
createProxiedComponent @ svelte-hooks.js:266
ProxyComponent @ proxy.js:239
Proxy<__layout> @ proxy.js:346
create_if_block_2 @ root.svelte? [sm]:37
create_fragment @ root.svelte? [sm]:36
init @ index.mjs:1877
Root @ root.svelte? [sm]:16
createProxiedComponent @ svelte-hooks.js:266
ProxyComponent @ proxy.js:239
Proxy<Root> @ proxy.js:346
_init @ start.js:885
start @ start.js:738
await in start (async)
(anonymous) @ (index):22369
VM4206:52 POST http://localhost:3000/undefined/auth/v1/token?grant_type=refresh_token 404 (Not Found)
XMLHttpRequest.send @ VM4206:52
(anonymous) @ browser-ponyfill.js:518
fetch2 @ browser-ponyfill.js:455
(anonymous) @ fetch.ts:50
(anonymous) @ fetch.ts:49
(anonymous) @ fetch.ts:1
__awaiter @ fetch.ts:1
_handleRequest @ fetch.ts:47
(anonymous) @ fetch.ts:75
(anonymous) @ fetch.ts:1
__awaiter @ fetch.ts:1
post @ fetch.ts:73
(anonymous) @ GoTrueApi.ts:386
(anonymous) @ helpers.ts:24
__awaiter2 @ helpers.ts:24
refreshAccessToken @ GoTrueApi.ts:383
(anonymous) @ GoTrueClient.ts:630
(anonymous) @ polyfills.ts:20
__awaiter3 @ polyfills.ts:20
_callRefreshToken @ GoTrueClient.ts:625
(anonymous) @ GoTrueClient.ts:602
fulfilled @ polyfills.ts:20
Promise.then (async)
step @ polyfills.ts:20
(anonymous) @ polyfills.ts:20
__awaiter3 @ polyfills.ts:20
_recoverAndRefresh @ GoTrueClient.ts:589
GoTrueClient @ GoTrueClient.ts:101
SupabaseAuthClient @ SupabaseAuthClient.ts:6
_initSupabaseAuthClient @ SupabaseClient.ts:232
SupabaseClient @ SupabaseClient.ts:77
createClient @ index.ts:21
(anonymous) @ supabase.ts:7
VM4683:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
```

**Comment by Ak4zh** [comment]
Sorry, I was missing the env variables.
Adding the supabase env variables fixed this.
